"""Multiple-testing control across the paper's positive claims.

The project runs many hypothesis tests; a referee will ask which discoveries
survive false-discovery-rate control. The inventory below is every POSITIVE
claim (an effect asserted to exist), and as of 2026-09-03 it no longer CARRIES
its p-values — it RE-DERIVES them from the frozen logs on every run.

That change has a history. The 2026-07-30 code review found the inventory
holding stale Jul-10 values; it was regenerated by hand (43bfb88), and by
2026-09-03 it had drifted again, in both directions, because a hand-maintained
list of numbers is a list of numbers that will go stale. So each claim now
names its log, a regex, and whether the captured quantity is a p or a z, and
the extractor reads it at runtime. A pattern that stops matching raises and
fails the suite, which is the point: a claim that cannot find its own evidence
must not be silently carried.

Each entry also records the value the inventory asserted BEFORE this refresh,
so main() prints a drift report rather than quietly overwriting the record.
Claims whose p-value has no single generating line are held OUT of the BH
family, following the precedent set when "Kalshi sharpens 24h->start" was
removed on the same grounds.

Policy (unchanged): cite the DATE-CLUSTERED p wherever a clustered and an
LR/MLE version both exist — the conservative choice. Nulls/equivalences are not
discoveries and are controlled by their own TOST margins; listed separately.
Benjamini-Hochberg at q = 0.05 and 0.10.

RETIRED CLAIMS (kept here as the honest record):
  - LADDER-CONVENTION CORRECTION (2026-08-20). MLB/WNBA spread rungs settle at
    "wins by t-0.5 or more"; NBA/NHL at "wins by more than t". The analysis
    layer applied the NBA rule everywhere, shifting MLB's implied margin CDF by
    a full run. Four claims below were that bug, not the market. Verified
    against Kalshi's own settlement field; guarded now by a data_audit gate and
    by src/analysis/ladder_convention.py.
      * "MLB ladder under-prices 1-2-run margins z=+10.05" -> +8.40pts becomes
        -1.10pts (z=-1.31). RETRACTED.
      * "MLB PIT rejects for Kalshi, KS p<0.001" -> KS 0.0709 becomes 0.0343,
        p=0.104. RETRACTED; every league's margin PIT now passes.
      * "Books beat Kalshi ladders as DISTRIBUTIONS, RPS z=+5.36" -> the MLB
        term was the artifact (+3.96e-3 z=+5.42 becomes +0.33e-3 z=+1.29).
        REVISED, not retracted: a smaller pooled edge survives (+0.49e-3,
        z=+2.44) and it is now carried by NBA (+1.14e-3, z=+2.27), whose
        convention was correct all along.
      * "Totals pass where margins reject" (the walk-off mechanism story) ->
        both layers now pass on the same 1,244 games (totals p=0.84, margins
        p=0.10). The CONTRAST is retracted; the totals result itself stands.
  - "Book consensus momentum z=17.5" (2026-07-21): 3-day small-sample
    artifact; matured panel own-lag z=-0.3.
  - "NBA carries the encompassing increment" (2026-07-30): p=0.006 on Jul-10
    data, p=0.145 on the current master — RETRACTED.
  - "Wide-set Kalshi beats Poly" and "log-score Kalshi beats book"
    (2026-07-30): the two long-flagged fragiles dissolved to p=0.142 / 0.326
    as the sample grew — no longer claims at any threshold.
  - "Kalshi sharpens 24h->start p=3e-4" (2026-07-30): no module in the
    current suite computes this statistic (descriptive table only); removed
    pending a proper constant-sample DM if wanted.
  - "WNBA totals PIT rejects, KS=0.108 p=.0076" (retired 2026-08-29, twice
    over): the freeze collection grew the sample 234->290 ladders and the
    rejection DISSOLVED in place (KS 0.062, p=0.207, mean u 0.509); and on
    the registered post-2026-08-12 holdout the tilt FLIPPED SIGN (mean u
    0.404, z=-2.3, n=47; oos_verification.log). A false alarm from the
    smallest league, caught by exactly the machinery built to catch it.
  - "Murphy sup-t: Kalshi edge vs Shin-book, low thresholds" (retired
    2026-09-03): the inventory carried p=0.037 from the Jul-30 era. The frozen
    log says the sup-t global p against the Shin-de-vigged book is 0.129
    (murphy.log). RETRACTED — it survives at no threshold, and it was always
    the claim most exposed to the de-vig choice. Found by the refactor that
    made this inventory read its own logs instead of remembering them.
"""
from __future__ import annotations

import re
from pathlib import Path

import numpy as np
from scipy import stats

LOGS = Path("results/logs")

# Each claim names the log that generates it, a regex over that log, and what
# the capture is ("p" = a p-value, "z" = a z-statistic converted two-sided).
# `was` is what the inventory asserted before the 2026-09-03 refresh, kept so
# drift is reported rather than silently absorbed.
SPECS = [
    dict(name="MLB extra-inning 1-2-run cell under-priced, BOTH venues",
         log="mlb_extras", kind="z", was=1e-8,
         pat=r"^\s*extras\s+[\d,]+\s+[\d.]+\s+[\d.]+\s+\+[\d.]+\s+\+([\d.]+)\s*$",
         note="ladder_vs_books: K +20.2pt / books +22.0pt on the same games — "
              "baseball-wide, not Kalshi-specific; regulation runs the other way"),
    dict(name="Extras end within 1 run vs regulation (two-proportion)",
         log="mlb_extras", kind="two_prop", was=1e-10,
         pat=r"regulation \(9 inn\)\s+([\d,]+)\s+([\d.]+).*?extra innings\s+([\d,]+)\s+([\d.]+)",
         note="the ghost-runner base rate the cell is mispriced against"),
    dict(name="Markets beat walk-forward Elo floor",
         log="model_benchmark", kind="z", was=1e-10,
         pat=r"model vs Kalshi\s+dBrier=\S+\s+z=\+([\d.]+)",
         note="weakest of the three venue comparisons is quoted"),
    dict(name="Minute-scale bidirectional K<->P predictability",
         log="minute_lead_lag", kind="z", was=1e-10,
         pat=r"dPoly <- Kalshi lags\s+sum-coef=\S+\s+z=\+([\d.]+)"),
    dict(name="Ladder-cost: selling MLB ladder rungs LOSES money",
         log="ladder_cost", kind="z", was=1e-5,
         pat=r"^\s*2\.5\s+[\d,]+\s+-[\d.]+%\s+-([\d.]+)\s*$",
         note="uses each contract's own settlement; not a Kalshi-specific bias"),
    dict(name="Poly relative volume falls at the fee date (DiD)",
         log="fee_liquidity", kind="z", was=3e-4,
         pat=r"MAIN:.*?z=-([\d.]+)"),
    dict(name="Books beat Kalshi ladders as DISTRIBUTIONS (pooled RPS)",
         log="multi_outcome", kind="z", was=1.5e-2,
         pat=r"^\s*ALL\s+n=\s*[\d,]+\s+RPS Kalshi=[\d.]+\s+book=[\d.]+\s+diff=\S+\s+z=\+([\d.]+)",
         note="post-convention-fix the edge is NBA-carried and small; MLB n.s."),
    dict(name="BOOKS' outright longshots overpriced (0-3mo, cluster-t)",
         log="book_outrights", kind="ratio_t", was=1e-5,
         pat=r"sub-10c: n=[\d,]+, \$1 -> \$([\d.]+) gross \(sport-season-clustered se ([\d.]+), (\d+) clusters\)",
         note="H0: $1 back per $1; t on 19 df — statistically identical to Kalshi's $0.33"),
    dict(name="Cross-venue 15-min predictability, P->K only",
         log="lead_lag", kind="z", was=1e-5,
         pat=r"predict dkalshi\s+<-.*?polymarket:\+[\d.]+\(z=\+([\d.]+)\)",
         note="the book->P term this claim once included is now z=-0.1 and retired"),
    dict(name="Book consensus predicts exchanges' next 5-min move (Poly)",
         log="five_min", kind="z", was=1e-5,
         pat=r"predict dpolymarket\s+<-.*?sportsbook:\+[\d.]+\(z=\+([\d.]+)\)",
         note="ZERO in the final 2h, lives in sub-0.5pt book moves, and as strong "
              "from a frozen quote — drift alignment, not news transmission"),
    dict(name="Late flow predicts beyond the closing book",
         log="late_flow", kind="p", was=1e-3,
         pat=r"K flow 24h->0\s+weight=\S+\s+clustered z=\+[\d.]+ p=([\d.]+)"),
    dict(name="Kalshi encompasses Polymarket at close",
         log="encompassing", kind="p", was=4.4e-2,
         pat=r"--- Kalshi \+ Polymarket \(n=[\d,]+\) ---\s*\n\s*kalshi\s+weight=\S+\s+clustered z=\+[\d.]+ p=([\d.]+)",
         note="FRAGILE — survives BH here, but this family has printed 0.004, "
              "0.048, 0.044, 0.054 and 0.021 across five vintages of the same "
              "claim: a result at the resolution limit, not a stable effect"),
    dict(name="Kalshi encompasses book at close",
         log="encompassing", kind="p", was=5.4e-2,
         pat=r"--- book \+ Kalshi \(n=[\d,]+\) ---\s*\n\s*book\s+.*\n\s*kalshi\s+weight=\S+\s+clustered z=\+[\d.]+ p=([\d.]+)",
         note="FRAGILE — same caveat as the K-vs-P term above"),
    dict(name="Books lead Kalshi at T-24h",
         log="horizon_equivalence", kind="p", was=6.3e-2,
         pat=r"Kalshi 24h - Book 24h:.*?z=\+[\d.]+ p=([\d.]+)",
         note="softened on the completed 84%-coverage T-24h sample"),
    dict(name="Murphy sup-t: Kalshi edge vs Shin-de-vigged book",
         log="murphy", kind="p", was=3.7e-2,
         pat=r"Kalshi\s+vs mult book: sup-t=[\d.]+ p=[\d.]+\s+\|\s+vs Shin book: sup-t=[\d.]+ p=([\d.]+)",
         note="RETRACTED 2026-09-03 — see the docstring; kept in the family so the "
              "BH computation is over the claims actually made, not a curated subset"),
]

# Claims with no single generating line. Held OUT of the BH family, following
# the "Kalshi sharpens 24h->start" precedent — the EFFECT is reported
# descriptively where it lives; the P-VALUE is what has no source.
UNSOURCED = [
    ("Sports FUTURES longshots overpriced ($0.33/$1, pooled)", 6e-3,
     "futures_calibration.log prints per-bucket exact binomials and a sub-10c "
     "$0.33 (se 0.28); no line computes the pooled p the inventory carried. "
     "Reported descriptively; needs a proper pooled test to re-enter the family."),
]


def logtext(name):
    return (LOGS / f"{name}.log").read_text()


# Below this, the normal tail underflows to exactly 0.0 in float64. Report the
# floor rather than "p=0", which claims more precision than the arithmetic has.
P_FLOOR = 1e-16


def two_sided(z):
    return max(float(2 * (1 - stats.norm.cdf(abs(z)))), P_FLOOR)


def extract(spec):
    """Pull this claim's statistic out of its log and return (p, evidence)."""
    m = re.search(spec["pat"], logtext(spec["log"]), re.M | re.S)
    if not m:
        raise AssertionError(
            f"multiple_testing: {spec['log']}.log no longer matches the pattern for "
            f"'{spec['name']}'. A claim that cannot find its evidence must not be "
            f"carried — fix the pattern or retire the claim.")
    k = spec["kind"]
    if k == "p":
        return float(m.group(1)), f"p={m.group(1)}"
    if k == "z":
        z = float(m.group(1))                      # magnitude; sign is in the log line
        return two_sided(z), f"|z|={z:.2f}"
    if k == "two_prop":
        n1, p1 = float(m.group(1).replace(",", "")), float(m.group(2))
        n2, p2 = float(m.group(3).replace(",", "")), float(m.group(4))
        pool = (p1 * n1 + p2 * n2) / (n1 + n2)
        se = np.sqrt(pool * (1 - pool) * (1 / n1 + 1 / n2))
        z = (p2 - p1) / se
        return two_sided(z), f"{p2:.3f} vs {p1:.3f}, |z|={abs(z):.2f}"
    if k == "ratio_t":
        ret, se, g = float(m.group(1)), float(m.group(2)), int(m.group(3))
        t = (ret - 1.0) / se
        return float(2 * stats.t.cdf(-abs(t), g - 1)), f"${ret:.2f} vs $1, t={t:+.2f} on {g-1} df"
    raise ValueError(k)


NULLS = [
    ("Three-way closing DM (all pairs)", "n.s. + TOST equivalent at ±1e-3"),
    ("Four-way: Poly-US vs each source", "n.s. + TOST equivalent at ±1e-3"),
    ("Fee natural experiment DiD on accuracy", "p=0.74 (placebo p=0.39)"),
    ("Taker-size markout gradient", "flat across quintiles"),
    ("Taker imbalance beyond book", "p=0.80/0.48"),
    ("Closing-price efficiency (move beyond close)", "p=0.99/0.35/0.52"),
    ("Behavioral fingerprints (home bias, franchise, weekend)", "all n.s."),
    ("FLB: all slope CIs include 1 (home-side)", "-"),
    ("Layer-2 main-line calibration (push-corrected)", "MLB 50.4% vs 49.9%; NBA n.s. — 45.0% claim retracted"),
    ("Kalshi margin PIT, all leagues (convention-corrected)", "pooled p=0.718; MLB p=0.104 — the pre-fix MLB rejection was the ladder-convention artifact. The BOOKS' far denser ladders show small deviations of their own (MLB p<.001, NHL p=.024, KS 0.04-0.07) — density/power, not superiority; see book_pit.log"),
    ("Kalshi TOTALS PIT, MLB", "KS=0.015 p=0.90 PASSES (n=1,466 ladders). The margin layer now ALSO passes post convention fix — the totals-pass/margins-reject contrast is retracted; both layers of the run process are priced correctly outside the extras cell"),
    ("Kalshi TOTALS PIT, NBA/NHL controls", "p=0.86 / 0.25 — pass on full samples (n=1,284 / 1,211)"),
    ("Kalshi totals right-tail bias (MLB)", "no threshold off by more than 2.8pt, all |z|<=1.01"),
    ("Totals ladder coherence, live-book only", "99.3-100% monotone every league; raw 86.9-95.6% is trade-reconstruction noise"),
    ("T-24h encompassing (K beyond book a day out)", "p=0.68"),
    ("Minute-scale first-passage leads", "median 0.0, sign-test p=1.0"),
    ("Resolution ladder 30->5 min: any venue leads", "no cross-lag corr sharpens as the clock sharpens; nothing predicts the book at any grid"),
    ("Book->exchange lead in the final 2h (5-min clock)", "K +0.006 (z=+0.1), P -0.008 (z=-0.1)"),
    ("Niche-sport games (no benchmark): excess ECE", "0.00pt vs noise floor; slope CI 0.84-1.15"),
    ("Exchanges vs PINNACLE at close (n=5,294)", "all n.s.; 90% CIs within ±0.34e-3 (TOST-equiv)"),
    ("Levitt shading vs sharp line (24 EU books)", "sub-1pt deviations, both signs"),
    ("Levitt shading, US retail (DK/FD/MGM +8, n=2.6K)", "-0.22..-0.01pt on home favs: none"),
    ("Book-by-book Brier vs Kalshi (11 US books)", "all n.s.; dead heat holds per book"),
    ("Poly outrights alone (22 fields)", "direction matches Kalshi, underpowered"),
]


def bh(items, q):
    """items: (name, p, note). Returns the BH ranking and how many survive."""
    m = len(items)
    ranked = sorted(items, key=lambda t: t[1])
    keep = 0
    for i, (_, p, _) in enumerate(ranked, start=1):
        if p <= i / m * q:
            keep = i
    return ranked, keep


def build():
    """Derive every discovery's p-value from the frozen logs, with drift."""
    rows = []
    for spec in SPECS:
        pv, ev = extract(spec)
        rows.append({**spec, "p": pv, "evidence": ev})
    return rows


def drift_report(rows):
    print("=== inventory drift: derived-from-logs vs what the inventory carried ===",
          flush=True)
    print("  (a hand-maintained p-value goes stale; this is why the list now reads", flush=True)
    print("   its own logs. 'was' is the pre-2026-09-03 asserted value.)\n", flush=True)
    print(f"  {'claim':<58}{'was':>10}{'now':>10}  {'evidence':<26} moved", flush=True)
    for r in sorted(rows, key=lambda r: r["p"]):
        ratio = r["p"] / r["was"] if r["was"] else float("inf")
        if r["p"] < 1e-4 and r["was"] < 1e-4:
            moved = "-"                       # both astronomically small
        elif 0.5 <= ratio <= 2.0:
            moved = "~same"
        else:
            moved = "WEAKER" if ratio > 1 else "stronger"
        now = f"<{P_FLOOR:.0g}" if r["p"] <= P_FLOOR else f"{r['p']:.2g}"
        print(f"  {r['name'][:57]:<58}{r['was']:>10.2g}{now:>10}  "
              f"{r['evidence']:<30} {moved}", flush=True)
    print(flush=True)


def main():
    rows = build()
    drift_report(rows)

    items = [(r["name"], r["p"], f"{r['log']}.log" +
              (f" [{r['note']}]" if r.get("note") else "")) for r in rows]
    for q in (0.05, 0.10):
        ranked, keep = bh(items, q)
        print(f"=== Benjamini-Hochberg, q={q} ({len(items)} positive claims, "
              f"p-values derived from the frozen logs at run time, clustered p "
              f"where available) ===", flush=True)
        for i, (name, pv, src) in enumerate(ranked, start=1):
            mark = "KEEP" if i <= keep else "drop"
            shown = f"<{P_FLOOR:.0g}" if pv <= P_FLOOR else f"{pv:.2g}"
            print(f"  [{mark}] p={shown:<8} {name}  ({src})", flush=True)
        print(flush=True)

    print("=== held OUT of the BH family: p-value has no generating line ===", flush=True)
    for name, was, why in UNSOURCED:
        print(f"  - {name} (inventory carried p={was:.2g})", flush=True)
        print(f"      {why}", flush=True)
    print(flush=True)

    print("=== nulls / equivalence claims (not FDR-controlled discoveries) ===", flush=True)
    for name, note in NULLS:
        print(f"  - {name}: {note}", flush=True)
    print("\n(retired claims documented in the module docstring)", flush=True)


if __name__ == "__main__":
    main()
